services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: liniker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teste
