CREATE TABLE IF NOT EXISTS products
(
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    product_value DECIMAL                                 NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id  BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    total      DECIMAL                                 NOT NULL,
    status     VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE TABLE tb_order_product
(
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_order_product PRIMARY KEY (order_id, product_id)
);

ALTER TABLE tb_order_product
    ADD CONSTRAINT fk_tbordpro_on_order_entity FOREIGN KEY (order_id) REFERENCES orders (order_id);

ALTER TABLE tb_order_product
    ADD CONSTRAINT fk_tbordpro_on_product_entity FOREIGN KEY (product_id) REFERENCES products (product_id);

CREATE TABLE IF NOT EXISTS clients
(
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (client_id)
);

ALTER TABLE orders
    ADD CONSTRAINT fk_order_entity_on_tb_cliord FOREIGN KEY (client_id) REFERENCES clients (client_id);

CREATE TABLE IF NOT EXISTS tb_client_order
(
    client_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_client_order PRIMARY KEY (client_id, order_id)
);

ALTER TABLE tb_client_order
    ADD CONSTRAINT fk_tbcliord_on_client_entity FOREIGN KEY (client_id) REFERENCES clients (client_id);

ALTER TABLE tb_client_order
    ADD CONSTRAINT fk_tbcliord_on_order_entity FOREIGN KEY (order_id) REFERENCES orders (order_id);
